services:
  - type: web
    name: banca-atlantis-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn BancaAtlantisBot:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.3
      - key: WEBSERVICE_MODE
        value: 1
      - key: BOT_TOKEN
        value: ""
